export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_CATEGORY = "SET_CATEGORY";
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const CURRENT_PAGE= "CURRENT_PAGE";

export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE FROM_CART";
export const INITIATE_CART = "INITIATE_CART"; 
export const INITIATE_RECEIPT = "INITIATE_RECEIPT";
export const FETCH_CART = "FETCH_CART";
export const POST_CART = "POST_CART";

export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR"